trigger:
  branches:
    include:
    - main
variables:
- name: pythonVersion
  value: '3.11'
- name: artifactName
  value: 'package-artifact'
- name: awsRegion
  value: 'us-east-1'
- name: major
  value: '1'
- name: minor
  value: '0'
- name: patch
  value: $[counter('patch', 1)]

stages:
- stage: Versioning
  displayName: Generate Version
  jobs:
  - job: VersionJob
    displayName: Generate SemVer
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        VERSION=$(major).$(minor).$(patch)
        echo "##vso[task.setvariable variable=appVersion;isOutput=true]$VERSION"
        echo "Generated version: $VERSION"
      name: SetVersion

- stage: Build
  dependsOn: Versioning
  variables:
    appVersion: $[ stageDependencies.Versioning.VersionJob.outputs['SetVersion.appVersion'] ]
  displayName: Continuous Integration
  jobs:
  - job: BuildJob
    displayName: Build and Test Application
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(pythonVersion)
      displayName: Use Python $(pythonVersion)

    - task: CmdLine@2
      displayName: Create pip cache directory
      inputs:
        script: |
          mkdir -p ~/.cache/pip

    - task: Cache@2
      inputs:
        key: 'python | "$(Agent.OS)" | requirements.txt'
        restoreKeys: |
          python | "$(Agent.OS)"
        path: $(Pipeline.Workspace)/.pip
      displayName: Cache pip dependencies

    - task: CmdLine@2
      displayName: Install dependencies
      inputs:
        script: |
          python -m pip install --upgrade pip
          pip install --cache-dir $(Pipeline.Workspace)/.pip -r requirements.txt

    - task: CmdLine@2
      displayName: Install lint tool
      inputs:
        script: |
          pip install flake8

    - task: CmdLine@2
      displayName: Run code linting
      inputs:
        script: |
          flake8 app --max-line-length=120

    - task: CmdLine@2
      displayName: Run unit tests
      inputs:
        script: python -m pytest

    - task: ArchiveFiles@2
      displayName: Package application
      inputs:
        rootFolderOrFile: $(Build.SourcesDirectory)
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(artifactName)-$(appVersion).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(artifactName)-$(appVersion).zip
      artifact: drop

- stage: Deploy
  displayName: Continuous Deployment
  dependsOn:
  - Build
  - Versioning
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
  - group: Susana Diez Gomez - Variables de Entorno
  - name: appVersion
    value: $[ stageDependencies.Versioning.VersionJob.outputs['SetVersion.appVersion'] ]
  jobs:
  - deployment: DeployAWS
    displayName: Deploy to AWS
    environment:
      name: Susana-Deploy
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AWSCLI@1
            displayName: Upload artifact to S3
            inputs:
              awsCredentials: AWS
              regionName: $(AWS_REGION)
              awsCommand: s3
              awsSubCommand: cp
              awsArguments: "$(Pipeline.Workspace)/drop/$(artifactName)-$(appVersion).zip s3://$(S3_BUCKET)/Susana-$(appVersion).zip"

          - task: AWSCLI@1
            displayName: Create application version
            inputs:
              awsCredentials: AWS
              regionName: $(AWS_REGION)
              awsCommand: elasticbeanstalk
              awsSubCommand: create-application-version
              awsArguments: >
                --application-name $(APPLICATION_NAME) --version-label Susana-$(appVersion) --source-bundle S3Bucket=$(S3_BUCKET),S3Key=Susana-$(appVersion).zip

          - task: AWSCLI@1
            name: CheckEnv
            displayName: Check and set environment existence
            inputs:
              awsCredentials: AWS
              regionName: $(AWS_REGION)
              awsCommand: elasticbeanstalk
              awsSubCommand: describe-environments
              awsArguments: >
                --environment-names $(ENVIRONMENT_NAME) --query "Environments[0].EnvironmentName" --output text

          - script: |
              echo "Environment exists: $ENV_EXISTS"
            displayName: Print environment check
            env:
              ENV_EXISTS: $(CheckEnv.AWSCLIOutput)

          - task: AWSCLI@1
            displayName: Create environment
            condition: eq(variables['CheckEnv'], 'None')
            inputs:
              awsCredentials: AWS
              regionName: $(AWS_REGION)
              awsCommand: elasticbeanstalk
              awsSubCommand: create-environment
              awsArguments: >
                --application-name $(APPLICATION_NAME) --environment-name $(ENVIRONMENT_NAME) --solution-stack-name "64bit Amazon Linux 2023 v4.11.0 running Python 3.11" --version-label Susana-$(appVersion)

          - task: AWSCLI@1
            name: GetEnvStatus
            displayName: Get Environment Status
            inputs:
              awsCredentials: AWS
              regionName: $(AWS_REGION)
              awsCommand: elasticbeanstalk
              awsSubCommand: describe-environments
              awsArguments: >
                --environment-names $(ENVIRONMENT_NAME)
                --query "Environments[0].Status"
                --output text

          - task: AWSCLI@1
            name: GetEnvHealth
            displayName: Get Environment Health
            inputs:
              awsCredentials: AWS
              regionName: $(AWS_REGION)
              awsCommand: elasticbeanstalk
              awsSubCommand: describe-environments
              awsArguments: >
                --environment-names $(ENVIRONMENT_NAME)
                --query "Environments[0].Health"
                --output text

          - task: AWSCLI@1
            displayName: Update environment
            condition: ne(variables['CheckEnv'], 'None')
            inputs:
              awsCredentials: AWS
              regionName: $(AWS_REGION)
              awsCommand: elasticbeanstalk
              awsSubCommand: update-environment
              awsArguments: >
                --environment-name $(ENVIRONMENT_NAME) --version-label Susana-$(appVersion)

          - task: AWSCLI@1
            displayName: Get Environment URL
            inputs:
              awsCredentials: AWS
              regionName: $(AWS_REGION)
              awsCommand: elasticbeanstalk
              awsSubCommand: describe-environments
              awsArguments: >
                --environment-names $(ENVIRONMENT_NAME) --query "Environments[0].CNAME" --output text
            name: GetURL