name: CI - Tests and Docker Build

# Define cuándo se ejecuta el pipeline
on:
  push:
    branches:
      - actividad-pipeline-ci
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias definidas en requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests
        run: |
          python -m pytest

      - name: Construir imagen Docker usando el Dockerfile del proyecto
        run: | 
          docker build -t actividad-pipeline-api .
